### ISSUE TITLE
Using sample configs throws pydantic error

### ISSUE THREAD

**Issue by albd** [debanjum/khoj#116]
```
Starting traefik_khoj_1 ... done
Attaching to traefik_khoj_1
khoj_1                  | Traceback (most recent call last):                                                                                                               khoj_1                  |   File "/usr/local/bin/khoj", line 8, in <module>
khoj_1                  |     sys.exit(run())
khoj_1                  |   File "/usr/local/lib/python3.10/site-packages/src/main.py", line 50, in run
khoj_1                  |     args = cli(state.cli_args)
khoj_1                  |   File "/usr/local/lib/python3.10/site-packages/src/utils/cli.py", line 36, in cli
khoj_1                  |     args.config = parse_config_from_file(args.config_file)
khoj_1                  |   File "/usr/local/lib/python3.10/site-packages/src/utils/yaml.py", line 39, in parse_config_from_file
khoj_1                  |     return parse_config_from_string(load_config_from_file(yaml_config_file))
khoj_1                  |   File "/usr/local/lib/python3.10/site-packages/src/utils/yaml.py", line 34, in parse_config_from_string
khoj_1                  |     return FullConfig.parse_obj(yaml_config)
khoj_1                  |   File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
khoj_1                  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
khoj_1                  | pydantic.error_wrappers.ValidationError: 1 validation error for FullConfig
khoj_1                  | processor -> conversation -> openai-api-key
khoj_1                  |   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by albd** [comment]
Sample configs don't provide lists to input filters.

**Comment by debanjum** [comment]
1. Pydantic is complaining that your `khoj.yml` has a `processor.conversation` section but without the required `openai-api-key` field set. You'll have to either delete the `processor.conversation` section from your `khoj.yml` or set the `openai-api-key` under the `processor.conversation` section

2. 

> Sample configs don't provide lists to input filters.

Do you mean the sample configs need to be updated to specify that `input-filter` expect lists? E.g in [khoj_sample.yml](https://github.com/debanjum/khoj/blob/master/config/khoj_sample.yml#L4):

<img width="719" alt="Screenshot 2023-01-08 at 20 02 10" src="https://user-images.githubusercontent.com/6413477/211223454-3c927585-8620-4128-80bd-6b3fa7b04d47.png">

**Comment by debanjum** [comment]
Updated the `khoj_sample.yml` and `khoj_docker.yml` to set `input-filter` to a list in 8b8e202
