### ISSUE TITLE
Can't install khoj-assistant on windows 11

### ISSUE THREAD

**Issue by g-berthiaume** [debanjum/khoj#131]
Hi!
Thanks for creating khoj.
I feel like there's a lot of interesting problem in making PKM more searchable.

Currently, I can't install khoj.

```powershell
λ  pip install khoj-assistant
Collecting khoj-assistant
  Using cached khoj_assistant-0.2.5-py3-none-any.whl (1.0 MB)
Collecting numpy==1.22.4
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting khoj-assistant
  Using cached khoj_assistant-0.2.1-py3-none-any.whl (828 kB)
  Using cached khoj_assistant-0.2.0-py3-none-any.whl (431 kB)
  Using cached khoj_assistant-0.1.10-py3-none-any.whl (431 kB)
  Using cached khoj_assistant-0.1.9-py3-none-any.whl (435 kB)
  Using cached khoj_assistant-0.1.8-py3-none-any.whl (433 kB)
  Using cached khoj_assistant-0.1.7-py3-none-any.whl (433 kB)
  Using cached khoj_assistant-0.1.6-py3-none-any.whl (429 kB)
  Using cached khoj_assistant-0.1.5-py3-none-any.whl (321 kB)
  Using cached khoj_assistant-0.1.4-py3-none-any.whl (142 kB)
  Using cached khoj_assistant-0.1.3-py3-none-any.whl (142 kB)
  Using cached khoj_assistant-0.1.2-py3-none-any.whl (142 kB)
  Using cached khoj_assistant-0.1.0-py3-none-any.whl (51 kB)
ERROR: Cannot install khoj-assistant==0.1.0, khoj-assistant==0.1.10, khoj-assistant==0.1.2, khoj-assistant==0.1.3, khoj-assistant==0.1.4, khoj-assistant==0.1.5, khoj-assistant==0.1.6, khoj-assistant==0.1.7, khoj-assistant==0.1.8, khoj-assistant==0.1.9, khoj-assistant==0.2.0, khoj-assistant==0.2.1 and khoj-assistant==0.2.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    khoj-assistant 0.2.5 depends on torch==1.13.1
    khoj-assistant 0.2.1 depends on torch==1.12.1
    khoj-assistant 0.2.0 depends on torch==1.12.1
    khoj-assistant 0.1.10 depends on torch==1.12.1
    khoj-assistant 0.1.9 depends on torch==1.12.1
    khoj-assistant 0.1.8 depends on torch==1.12.1
    khoj-assistant 0.1.7 depends on torch==1.12.1
    khoj-assistant 0.1.6 depends on torch==1.11.0
    khoj-assistant 0.1.5 depends on torch==1.11.0
    khoj-assistant 0.1.4 depends on torch==1.11.0
    khoj-assistant 0.1.3 depends on torch==1.11.0
    khoj-assistant 0.1.2 depends on torch==1.11.0
    khoj-assistant 0.1.0 depends on torch==1.11.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

![image](https://user-images.githubusercontent.com/19377511/216790486-0d5c5444-adb7-429a-8966-9819c3c7e70e.png)

**Comment by debanjum** [comment]
Hey @g-berthiaume, thanks for the kind words!

Another user recently hit [the same issue](https://github.com/debanjum/khoj/issues/128#issuecomment-1416051558) as well. 
1. You can mitigate the issue by downgrading to python 3.9 instead of python 3.11
2. Or if you can wait a few days, I'll investigate and (hopefully) fix the issue with making khoj work with python 3.11

**Comment by g-berthiaume** [comment]
That's great. 
I'll wait for the patch.

Take care.

**Comment by DeutscheGabanna** [comment]
I was getting similar problems as mentioned in the #128, and downgraded to python 3.9 from 3.11 something.
Now I'm getting this error:

```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 67, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
```

**Comment by debanjum** [comment]
Hi @DeutscheGabanna, I saw a few other folks complain about this PyQt issue as well. So I've created a separate issue #145 to track the investigation and fix for it
