### ISSUE TITLE
Fail to install khoj due to PyQt error

### ISSUE THREAD

**Issue by debanjum** [debanjum/khoj#145]
_Originally posted by @DeutscheGabanna in https://github.com/debanjum/khoj/issues/131#issuecomment-1419871641_

I was getting similar problems as mentioned in the #128, and downgraded to python 3.9 from 3.11 something.
Now I'm getting this error:

```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 67, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-9iau_fe6\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
```

**Comment by DeutscheGabanna** [comment]
Leaving this as suggested by you:
```
python -m pip install khoj-assistant==0.2.6
Collecting khoj-assistant==0.2.6
  Downloading khoj_assistant-0.2.6-py3-none-any.whl (1.0 MB)
     ---------------------------------------- 1.0/1.0 MB 16.4 MB/s eta 0:00:00
Collecting pydantic==1.9.1
  Using cached pydantic-1.9.1-py3-none-any.whl (142 kB)
Collecting pillow==9.3.0
  Using cached Pillow-9.3.0-cp39-cp39-win32.whl (2.2 MB)
Collecting transformers==4.21.0
  Using cached transformers-4.21.0-py3-none-any.whl (4.7 MB)
Collecting schedule==1.1.0
  Using cached schedule-1.1.0-py2.py3-none-any.whl (10 kB)
Collecting fastapi==0.77.1
  Using cached fastapi-0.77.1-py3-none-any.whl (54 kB)
Collecting defusedxml==0.7.1
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting numpy==1.22.4
  Using cached numpy-1.22.4-cp39-cp39-win32.whl (12.2 MB)
Collecting openai==0.20.0
  Using cached openai-0.20.0.tar.gz (42 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyqt6==6.3.1
  Using cached PyQt6-6.3.1.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-pwi35v7h\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-pwi35v7h\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-pwi35v7h\overlay\Lib\site-packages\sipbuild\project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 67, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-pwi35v7h\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-pwi35v7h\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\Paul\AppData\Local\Temp\pip-build-env-pwi35v7h\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\Paul>where python
C:\Users\Paul\AppData\Local\Programs\Python\Python39-32\python.exe

C:\Users\Paul>
```

I followed all the advice I could get from both this repository as well as PyQt6 help channels.

    I ran python -m pip install instead just pip install to make sure I invoke the correct Python version
    I only have python 3.9 so whatever, actually, but I was told 3.9 is the version where khoji actually works
    I ran where python to also make sure I launch from python 3.9
    I used the latest version of khoji==0.2.6

**Comment by DeutscheGabanna** [comment]
sorry for the duplicate

**Comment by debanjum** [comment]
No issues! Thanks for adding your investigation here. I'll try get to this by next week

**Comment by DeutscheGabanna** [comment]
OH MY GOD! I FIXED IT!
I ran so many commands that it may be hard to pin-point which one worked in which order, but I'll try. Maybe it'll help you investigate the issue further.

The "success" route is something like this:

- install python 3.9-x86-64 version (the 64-bit version, not 32-bit one)
```
py -3.9.64 -m pip install --upgrade pip
py -3.9.64 -m pip install khoj-assistant
py -3.9.64 -m pip install -U sentence-transformers --no-warn-script-location
C:\Users\%USER%\AppData\Local\Programs\Python\Python39\Scripts\khoj.exe --no-gui
```

**Comment by DeutscheGabanna** [comment]
I got the server running. I do not know if this is the kind of error that stops the entire program from running, but I've seen this in the backend log:
```
c:\users\paul\appdata\local\programs\python\python39\lib\site-packages\huggingface_hub\file_download.py:560: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 737kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 190kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 11.5k/11.5k [00:00<00:00, 5.76MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 612/612 [00:00<00:00, 612kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 116/116 [00:00<00:00, 116kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 25.5k/25.5k [00:00<00:00, 245kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 349kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 90.9M/90.9M [00:01<00:00, 78.5MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 53.0/53.0 [00:00<00:00, 26.5kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 112kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 812kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 383/383 [00:00<00:00, 192kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 13.8k/13.8k [00:00<00:00, 128kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 546kB/s]
Downloading config.json: 100%|█████████████████████████████████████████████████████████| 794/794 [00:00<00:00, 793kB/s]
Downloading pytorch_model.bin: 100%|██████████████████████████████████████████████| 86.7M/86.7M [00:01<00:00, 80.2MB/s]
Downloading tokenizer_config.json: 100%|███████████████████████████████████████████████| 316/316 [00:00<00:00, 315kB/s]
Downloading vocab.txt: 100%|█████████████████████████████████████████████████████████| 226k/226k [00:00<00:00, 511kB/s]
Downloading special_tokens_map.json: 100%|█████████████████████████████████████████████| 112/112 [00:00<00:00, 112kB/s]
ERROR: 2023-02-10 19:41:57,463: src.routers.api | 'charmap' codec can't encode character '\u0142' in position 2490: character maps to <undefined>
```

**Comment by DeutscheGabanna** [comment]
I looked up the character that bricked the codec and it seems my Polish diacritics are dangerous for your program :D 
https://www.fileformat.info/info/unicode/char/0142/index.htm

it's just an innocent `ł`

**Comment by DeutscheGabanna** [comment]
Maybe something like this would help?
```
with open(fname, "w", encoding="utf-8") as f:
    f.write(html)
```

**Comment by debanjum** [comment]
> OH MY GOD! I FIXED IT!

That's great! 🎉

> The "success" route is something like this:
>
>   install python 3.9-x86-64 version

Noted! Will ask the next person hitting the issue to try above and mark this issue as completed if that fixes the PyQt error for them.

**Comment by debanjum** [comment]
> `ERROR: 2023-02-10 19:41:57,463: src.routers.api | 'charmap' codec can't encode character '\u0142' in position 2490: character maps to <undefined>`

You now seem to be hitting issue related to #89, More specifically, the same error as reported in [this reddit comment](https://www.reddit.com/r/ObsidianMD/comments/10thrpl/comment/j78b5lt/). But this specific issue should have resolved for khoj version 0.2.6.

Based on your earlier comments it seems like you're on khoj 0.2.6. But can you still share the khoj version you're using by running `khoj -V`? And try these fixes:
1. Upgrade your khoj backend by running `py -3.9.64 -m pip install --upgrade khoj-assistant`
2. Delete your the khoj directory at `c:\users\<your-username>\.khoj` and restart khoj with `khoj --no-gui -vv`

> Maybe something like this would help?
> ```python
> with open(fname, "w", encoding="utf-8") as f:
>    f.write(html)
> ```

Yeah, the open markdown files with utf-8 encoding was effectively what was done as a fix for the issue in https://github.com/debanjum/khoj/commit/99a03da3f79eed24e5a7dcef3d2b15faa0926366

> it seems my Polish diacritics are dangerous for your program :D

😅🙈

> it's just an innocent ł

They're apparently not as innocent as they look 😅. Can you share the encoding used by the file containing the above polish diacritic? It should be utf-8, but just want to double confirm that. See this [stackoverflow post](https://stackoverflow.com/a/13464816) on finding files encoding

**Comment by debanjum** [comment]
> ERROR: 2023-02-10 19:41:57,463: src.routers.api | 'charmap' codec can't encode character '\u0142' in position 2490: character maps to <undefined>

Hey @DeutscheGabanna,

I just pushed a (potential) fix for this issue in https://github.com/debanjum/khoj/commit/11517ba8eb3a968f1100caaedd3043d9310cf230.

It'd be great if you can try the following steps:
1. Delete the `.khoj` directory in your home folder (usually at `C:\Users\%USER%\.khoj` on Windows)
2. Upgrade khoj to latest pre-release version with `py -3.9.64 -m pip install --upgrade --pre khoj-assistant`
3. (Re-)start khoj backend with `C:\Users\%USER%\AppData\Local\Programs\Python\Python39\Scripts\khoj.exe --no-gui`
4. Reinstall/re-enable the Khoj Obsidian plugin

Hopefully that should resolve the above issue for you 🤞🏾

**Comment by hewcaw** [comment]
> It'd be great if you can try the following steps:

Thanks bro, this works beautifully!

**Context** - At first I tried with `3.11.2` but I can't installed `khoj`, then I switched to `3.10.9`. I can installed it, but when I setting up Obsidian, after download something (the models?) from HuggingFace I faced the same error, I cannot search anything, even cannot rerun `khoj` after cancelling it, thought it was a problem with `numpy`'s version. Then I went and tried this, after processing some batches (IDK anything about ML), then I can search with `khoj`.

**Comment by hewcaw** [comment]
> When you say you faced the same error do you mean:

The `'charmap'` one — `ERROR: 2023-02-14 15:44:57,662: src.routers.api | 'charmap' codec can't encode characters in position 971-972: character maps to <undefined>` when installing.

The `numpy` is probably because I forgot to add `--no-gui` when run `khoj`.

**Comment by debanjum** [comment]
I see, thanks for clarifying that!

Yeah, using the latest pre-release version of khoj (after deleting the `~/.khoj` directory) should have fixed the `charmap` error (and the numpy error?).

**Comment by DeutscheGabanna** [comment]
I believe the issue is now resolved on my end. Thank you so much for assistance!
