### ISSUE TITLE
Bug: Invalid Argument from something date related

### ISSUE THREAD

**Issue by ggstrader** [debanjum/khoj#172]
Sorry I don't have much time to investigate this at the moment, just looking for some aid to get up and running.
I'm on Windows 10, 
I've run:
```powershell
python3 -m venv env
cd .\env\
.\Scripts\activate
python --version # Python 3.9.13
pipenv install khoj-assistant # Installation was successful
khoj --no-gui # error after running
```

 The error:
```
khoj --no-gui
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [06:37<00:00,  3.93s/it]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\env\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "E:\env\lib\site-packages\khoj\main.py", line 80, in run
    configure_server(args, required=False)
  File "E:\env\lib\site-packages\khoj\configure.py", line 44, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "E:\env\lib\site-packages\khoj\configure.py", line 82, in configure_search
    model.markdown_search = text_search.setup(
  File "E:\env\lib\site-packages\khoj\search_type\text_search.py", line 185, in setup
    filter.load(entries, regenerate=regenerate)
  File "E:\env\lib\site-packages\khoj\search_filter\date_filter.py", line 41, in load
    date_in_entry = datetime.strptime(date_in_entry_string, "%Y-%m-%d").timestamp()
OSError: [Errno 22] Invalid argument
```

**Comment by debanjum** [comment]
Sounds like a bug. I'll push a fix for it soon.

**Comment by debanjum** [comment]
Hey @ggstrader, I pushed a mitigation for the issue you were facing with the date filters. Let me know if the issue still persists after upgrade khoj with `pip install --upgrade khoj-assistant` (or the equivalent command for `pipenv`)

**Comment by ggstrader** [comment]
It runs now, and I can visit it at http://127.0.0.1:8000/ and see it working!
However the obsidian plugin got a 404

**Comment by ggstrader** [comment]
Oh, it was two things:
1. I had something else running on that port
2. when switching ports, I needed to remove the trailing slash from the URL
