### ISSUE TITLE
Error "'utf-8' codec can't decode byte 0xaf"

### ISSUE THREAD

**Issue by grepinsight** [debanjum/khoj#175]
Excited to try this out, but I am getting following errors:

```bash
└─> khoj --no-gui
[00:10:19] WARNING  Khoj is not configured.                                                                                                      configure.py:32
                    Configure it via khoj GUI, plugins or by editing /Users/allee/.khoj/khoj.yml.
[00:10:20] INFO     Started server process [17775]                                                                                                  server.py:75
           INFO     Waiting for application startup.                                                                                                    on.py:45
           INFO     Application startup complete.                                                                                                       on.py:59
           INFO     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)                                                                server.py:206
[00:10:47] INFO     127.0.0.1:57519 - "GET / HTTP/1.1" 200                                                                                       h11_impl.py:431
           INFO     127.0.0.1:57519 - "GET /assets/org.min.js HTTP/1.1" 200                                                                      h11_impl.py:431
           INFO     127.0.0.1:57520 - "GET /assets/markdown-it.min.js HTTP/1.1" 200                                                              h11_impl.py:431
           INFO     127.0.0.1:57520 - "GET /api/config/data HTTP/1.1" 200                                                                        h11_impl.py:431
           INFO     127.0.0.1:57522 - "GET /khoj.webmanifest HTTP/1.1" 200                                                                       h11_impl.py:431
           INFO     127.0.0.1:57520 - "GET /assets/icons/favicon-144x144.png HTTP/1.1" 200                                                       h11_impl.py:431
[00:10:51] INFO     127.0.0.1:57520 - "GET /api/update?t= HTTP/1.1" 422                                                                          h11_impl.py:431
[00:10:58] INFO     127.0.0.1:57523 - "GET /api/update?t= HTTP/1.1" 422                                                                          h11_impl.py:431
[00:10:59] INFO     127.0.0.1:57523 - "GET /api/update?t= HTTP/1.1" 422                                                                          h11_impl.py:431
[00:11:09] INFO     127.0.0.1:57525 - "GET /api/config/data HTTP/1.1" 200                                                                        h11_impl.py:431
           INFO     127.0.0.1:57525 - "GET /api/config/data/default HTTP/1.1" 200                                                                h11_impl.py:431
           INFO     127.0.0.1:57525 - "GET /api/config/data/default HTTP/1.1" 200                                                                h11_impl.py:431
           INFO     127.0.0.1:57525 - "POST /api/config/data HTTP/1.1" 200                                                                       h11_impl.py:431
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [███████████████████████████████████████████████████████████| 116/116 [0
[00:12:14] ERROR    'utf-8' codec can't decode byte 0xaf in position 14: invalid start byte  
```

```bash
└─> khoj --no-gui
Traceback (most recent call last):
  File "/Users/grepinsight/miniconda3/envs/jupyter/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/Users/grepinsight/miniconda3/envs/jupyter/lib/python3.9/site-packages/khoj/main.py", line 80, in run
    configure_server(args, required=False)
  File "/Users/grepinsight/miniconda3/envs/jupyter/lib/python3.9/site-packages/khoj/configure.py", line 44, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "/Users/grepinsight/miniconda3/envs/jupyter/lib/python3.9/site-packages/khoj/configure.py", line 82, in configure_search
    model.markdown_search = text_search.setup(
  File "/Users/grepinsight/miniconda3/envs/jupyter/lib/python3.9/site-packages/khoj/search_type/text_search.py", line 170, in setup
    entries_with_indices = text_to_jsonl(config).process(previous_entries)
  File "/Users/grepinsight/miniconda3/envs/jupyter/lib/python3.9/site-packages/khoj/processor/markdown/markdown_to_jsonl.py", line 40, in process
    *MarkdownToJsonl.extract_markdown_entries(markdown_files)
  File "/Users/grepinsight/miniconda3/envs/jupyter/lib/python3.9/site-packages/khoj/processor/markdown/markdown_to_jsonl.py", line 110, in extract_markdown_entries
    markdown_content = f.read()
  File "/Users/grepinsight/miniconda3/envs/jupyter/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 14: invalid start byte
```

**Comment by debanjum** [comment]
I'd made some file encoding related bugs in https://github.com/debanjum/khoj/issues/89. But seems like we still haven't cleared all of them up. 

- Are you trying to use Khoj with Obsidian?
- What is the file encoding of your markdown files?

This is unexpected if you are using Obsidian. As based on [my earlier readings](https://forum.obsidian.md/t/better-handle-md-files-not-stored-in-utf8-format/13524/10) it seems like Obsidian stores all markdown files in your vault with utf8 encoding. So Khoj trying to read the same markdown files in your vault as utf-8 shouldn't ideally fail with the unicode decode error. 🤔 

It'd be great if you can identify the file/character causing this issue. It'll help investigating this issue

The fastest/simplest way to mitigate this issue on your side (and start using khoj) maybe be to identify the non-utf8 encoded markdown files in your vault and convert them to utf8.

The more involved fix mentioned in point `3.` of [this issue comment](https://github.com/debanjum/khoj/issues/89#issuecomment-1435363090) can be prioritized if this issue persists or is more widespread than earlier suspected

**Comment by debanjum** [comment]
I'll close this issue as we don't have enough data to reproduce the issue and the issue may have already been fixed. For example in: https://github.com/debanjum/khoj/commit/d90df966a9fd2e62250dbbc922210707b486c796
