### ISSUE TITLE
Null Reference Error on starting Khoj with GUI on First Run

### ISSUE THREAD

**Issue by onekum** [debanjum/khoj#176]
```
[useruser@archlinux ~]$ khoj
Traceback (most recent call last):
  File "/home/useruser/.local/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/home/useruser/.local/lib/python3.10/site-packages/khoj/main.py", line 85, in run
    main_window = MainWindow(args.config_file)
  File "/home/useruser/.local/lib/python3.10/site-packages/khoj/interface/desktop/main_window.py", line 62, in __init__
    self.search_settings_panels += [self.add_settings_panel(current_content_config, search_type)]
  File "/home/useruser/.local/lib/python3.10/site-packages/khoj/interface/desktop/main_window.py", line 87, in add_settings_panel
    current_content_files = current_content_config.get("input-files", [])
AttributeError: 'NoneType' object has no attribute 'get'
```
Hi, I've gotten another error, this time when trying to start khoj for the second time using the command `khoj`. I'm using: `Python 3.10.9`. I searched for similar issues but couldn't find this exact error in any other open or closed issues, so I'm sorry if this is a duplicate.

**Comment by debanjum** [comment]
Ugh, yeah there is a null reference bug when you start khoj in gui mode on first run.
To avoid this, start khoj with `khoj --no-gui` instead. Then install/enable your Khoj obsidian plugin.

Starting khoj in no-gui mode should bypass the above issue. I'll push a fix for it in a day or two

**Comment by debanjum** [comment]
See #167 for previous issue on same topic
