### ISSUE TITLE
"ImportError: libGL.so.1" when launched with docker-compose 

### ISSUE THREAD

**Issue by whym** [debanjum/khoj#76]
My environment is Ubuntu 22.04.1 LTS. I tried `docker-compose up -d` and `docker-compose logs` and the latter says:
```
Attaching to khoj_server_1
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/bin/khoj", line 5, in <module>
server_1  |     from src.main import run
server_1  |   File "/usr/local/lib/python3.10/site-packages/src/main.py", line 12, in <module>
server_1  |     from PyQt6 import QtWidgets
server_1  | ImportError: libGL.so.1: cannot open shared object file: No such file or directory

```

http://0.0.0.0:8000/ is not accessible.

**Comment by debanjum** [comment]
Thanks for the bug report! I was able to reproduce the issue.
@whym let me know if you aren't still able to run Khoj using docker once the PR #77 is merged.
