### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by AriT93** [debanjum/khoj#78]
Was interested in trying this out after the Reddit post.  However after pip install khoj-assistant && khoj I get this error and khoj dies

`❯ khoj
/usr/local/lib/python3.9/site-packages/huggingface_hub/snapshot_download.py:6: FutureWarning: snapshot_download.py has been made private and will no longer be available from version 0.11. Please use `from huggingface_hub import snapshot_download` to import the only public function in this module. Other members of the file may be changed without a deprecation notice.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/src/main.py", line 93, in run
    main_window = MainWindow(args.config_file)
  File "/usr/local/lib/python3.9/site-packages/src/interface/desktop/main_window.py", line 62, in __init__
    self.search_settings_panels += [self.add_settings_panel(current_content_config, search_type)]
  File "/usr/local/lib/python3.9/site-packages/src/interface/desktop/main_window.py", line 95, in add_settings_panel
    input_files = FileBrowser(file_input_text, search_type, current_content_files)
  File "/usr/local/lib/python3.9/site-packages/src/interface/desktop/file_browser.py", line 28, in __init__
    self.setFiles(default_files)
  File "/usr/local/lib/python3.9/site-packages/src/interface/desktop/file_browser.py", line 62, in setFiles
    self.filepaths = [path for path in paths if not is_none_or_empty(path)]
TypeError: 'NoneType' object is not iterable`

could be local python setup .  This is on MacOS Monterey

**Comment by debanjum** [comment]
Thanks for the bug report! The issue should be fixed in PR #81.
You can upgrade and run Khoj with `pip install --upgrade khoj-assistant && khoj`.
Let me know if you still face any issues.
