### ISSUE TITLE
khoj-assistant errors on Arch Linux

### ISSUE THREAD

**Issue by emacsomancer** [debanjum/khoj#79]
On Arch Linux, if install khoj-assistant via pip and then run `khoj`, I get the following error:

```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "/home/slade/.local/bin/khoj", line 5, in <module>
    from src.main import run
  File "/home/slade/.local/lib/python3.10/site-packages/src/main.py", line 16, in <module>
    from src.configure import configure_server
  File "/home/slade/.local/lib/python3.10/site-packages/src/configure.py", line 12, in <module>
    from src.search_type import image_search, text_search
  File "/home/slade/.local/lib/python3.10/site-packages/src/search_type/image_search.py", line 11, in <module>
    from sentence_transformers import SentenceTransformer, util
  File "/home/slade/.local/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/slade/.local/lib/python3.10/site-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/home/slade/.local/lib/python3.10/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/home/slade/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 25, in <module>
    from .evaluation import SentenceEvaluator
  File "/home/slade/.local/lib/python3.10/site-packages/sentence_transformers/evaluation/__init__.py", line 3, in <module>
    from .BinaryClassificationEvaluator import BinaryClassificationEvaluator
  File "/home/slade/.local/lib/python3.10/site-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 5, in <module>
    from sklearn.metrics.pairwise import paired_cosine_distances, paired_euclidean_distances, paired_manhattan_distances
  File "/home/slade/.local/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/slade/.local/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/slade/.local/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 22, in <module>
    from scipy.sparse import issparse
  File "/usr/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 267, in <module>
    from ._csr import *
  File "/usr/lib/python3.10/site-packages/scipy/sparse/_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import
```

If I then force update `numpy` (via `pip install numpy --upgrade`, and create `~/.khoj` and `touch `~/.khoj/khoj.log`), then I get the error:

```
/home/slade/.local/lib/python3.10/site-packages/huggingface_hub/snapshot_download.py:6: FutureWarning: snapshot_download.py has been made private and will no longer be available from version 0.11. Please use `from huggingface_hub import snapshot_download` to import the only public function in this module. Other members of the file may be changed without a deprecation notice.
  warnings.warn(
Traceback (most recent call last):
  File "/home/slade/.local/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/home/slade/.local/lib/python3.10/site-packages/src/main.py", line 93, in run
    main_window = MainWindow(args.config_file)
  File "/home/slade/.local/lib/python3.10/site-packages/src/interface/desktop/main_window.py", line 62, in __init__
    self.search_settings_panels += [self.add_settings_panel(current_content_config, search_type)]
  File "/home/slade/.local/lib/python3.10/site-packages/src/interface/desktop/main_window.py", line 95, in add_settings_panel
    input_files = FileBrowser(file_input_text, search_type, current_content_files)
  File "/home/slade/.local/lib/python3.10/site-packages/src/interface/desktop/file_browser.py", line 28, in __init__
    self.setFiles(default_files)
  File "/home/slade/.local/lib/python3.10/site-packages/src/interface/desktop/file_browser.py", line 62, in setFiles
    self.filepaths = [path for path in paths if not is_none_or_empty(path)]
TypeError: 'NoneType' object is not iterable
```

Edit: And if I try installing via conda, I end up with the same second error (the `huggingface` one); given other issues on other platforms (e.g. https://github.com/debanjum/khoj/issues/78 ) I suspect this is not an Arch-specific issue (or probably a Python 3.10 specific issue either).

**Comment by debanjum** [comment]
Thanks for the bug report! 

PR #81 fixed the two (main?) issues below:
1. You shouldn't need to manually create the app directory anymore
2. The unexpected NoneType issues should be fixed

For the other two issues you mention:
  - I don't see the huggingface issue in the logs you shared but you can ignore the
`huggingface_hub/snapshot_download.py:6: FutureWarning: snapshot_download.py has been made private...` warning for now. It's for an upstream package.
  - You seem to have found the resolution for the numpy issue yourself (`pip install --upgrade numpy`). I'll investigate how to avoid it, if possible. But this shouldn't affect most users.

Khoj should (hopefully) work fine if you upgrade and run with `pip install --upgrade khoj-assistant && khoj`.
Let me know if you still face any issues.
