### ISSUE TITLE
Error installing on Manjaro

### ISSUE THREAD

**Issue by arozbiz** [debanjum/khoj#80]
After using pip to install khoj, I get the following error when running khoj:

```
/home/alan/.local/lib/python3.10/site-packages/huggingface_hub/snapshot_download.py:6: FutureWarning: snapshot_download.py has been made private and will no longer be available from version 0.11. Please use `from huggingface_hub import snapshot_download` to import the only public function in this module. Other members of the file may be changed without a deprecation notice.
  warnings.warn(
Traceback (most recent call last):
  File "/home/alan/.local/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/home/alan/.local/lib/python3.10/site-packages/src/main.py", line 80, in run
    fh = logging.FileHandler(state.config_file.parent / 'khoj.log')
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/alan/.khoj/khoj.log'
```

If I manually create the .khoj folder and an empty khoj.log file, I get this error:
```
/home/alan/.local/lib/python3.10/site-packages/huggingface_hub/snapshot_download.py:6: FutureWarning: snapshot_download.py has been made private and will no longer be available from version 0.11. Please use `from huggingface_hub import snapshot_download` to import the only public function in this module. Other members of the file may be changed without a deprecation notice.
  warnings.warn(
Traceback (most recent call last):
  File "/home/alan/.local/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/home/alan/.local/lib/python3.10/site-packages/src/main.py", line 93, in run
    main_window = MainWindow(args.config_file)
  File "/home/alan/.local/lib/python3.10/site-packages/src/interface/desktop/main_window.py", line 62, in __init__
    self.search_settings_panels += [self.add_settings_panel(current_content_config, search_type)]
  File "/home/alan/.local/lib/python3.10/site-packages/src/interface/desktop/main_window.py", line 95, in add_settings_panel
    input_files = FileBrowser(file_input_text, search_type, current_content_files)
  File "/home/alan/.local/lib/python3.10/site-packages/src/interface/desktop/file_browser.py", line 28, in __init__
    self.setFiles(default_files)
  File "/home/alan/.local/lib/python3.10/site-packages/src/interface/desktop/file_browser.py", line 62, in setFiles
    self.filepaths = [path for path in paths if not is_none_or_empty(path)]
TypeError: 'NoneType' object is not iterable
```

**Comment by debanjum** [comment]
Thanks for the bug report! The issue you saw is the same as #78. It's been resolved in PR #81.
You can upgrade and run Khoj with `pip install --upgrade khoj-assistant && khoj`.
Let me know if you still face any issues.
