### ISSUE TITLE
khoj-assistant errors on manjaro

### ISSUE THREAD

**Issue by bommbo** [debanjum/khoj#94]
```
Traceback (most recent call last):
  File "/home/ea/.local/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/home/ea/.local/lib/python3.10/site-packages/src/main.py", line 67, in run
    args = cli(state.cli_args)
  File "/home/ea/.local/lib/python3.10/site-packages/src/utils/cli.py", line 36, in cli
    args.config = parse_config_from_file(args.config_file)
  File "/home/ea/.local/lib/python3.10/site-packages/src/utils/yaml.py", line 38, in parse_config_from_file
    return parse_config_from_string(load_config_from_file(yaml_config_file))
  File "/home/ea/.local/lib/python3.10/site-packages/src/utils/yaml.py", line 33, in parse_config_from_string
    return FullConfig.parse_obj(yaml_config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for FullConfig
content-type -> org -> input-filter
  Either input_filter or input_files required in all content-type.<text_search> section of Khoj config file (type=value_error)
content-type -> ledger -> input-filter
  Either input_filter or input_files required in all content-type.<text_search> section of Khoj config file (type=value_error)
content-type -> image -> input-filter
  Either input_filter or input_directories required in all content-type.image section of Khoj config file (type=value_error)
content-type -> music -> input-filter
  Either input_filter or input_files required in all content-type.<text_search> section of Khoj config file (type=value_error)
processor -> conversation -> openai-api-key
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by debanjum** [comment]
- It seems the `~/.khoj/khoj.yml` to configure khoj doesn't have required fields for enabled content types (like `input-files`, `input-filter` and `openai-api-key`. You'll need to set the files to index for the content type you want to enable or disable that content-type. 
- Are you using the GUI to configure the app? If so, can you share a screenshot of how it looks? Otherwise if you're editing the `~/.khoj/khoj.yml` file directly, it'd be great if you can share how that looks
